source 'https://rubygems.org'
gem 'rails'
gem 'httpclient'
gem 'sass-rails'
gem 'haml'
gem 'virtus'
gem 'simple_form'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'foundation-rails'
