source 'https://rubygems.org'
gem 'rails'
gem 'httpclient'
gem 'sass-rails'
gem 'haml'
gem 'virtus'
gem 'bootstrap_form'
gem 'draper'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'bootstrap-sass'
gem 'parsley-rails'
